project:
  type: website

name: "dku-stats-101"

website:
  title: "DKU Stats 101 - Spring 2023"
  navbar: 
    left:
      - text: "Course Introduction"
        href: index.html
      - text: "Schedule and Course Materials"
        href: schedulematerials.html
      - text: "Homework"
        href: homework.html
      - text: "R Help Manual"
        href: rmanual.html
    right: 
      - icon: fa-github fa-lg
        href: https://github.com/andrewmacd/dkustats101spring2023

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

output_dir: "docs"

