<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Anonymous">
<meta name="dcterms.date" content="2023-03-31">

<title>Homework 1 Sample Solutions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Homework 1 Sample Solutions_files/libs/clipboard/clipboard.min.js"></script>
<script src="Homework 1 Sample Solutions_files/libs/quarto-html/quarto.js"></script>
<script src="Homework 1 Sample Solutions_files/libs/quarto-html/popper.min.js"></script>
<script src="Homework 1 Sample Solutions_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Homework 1 Sample Solutions_files/libs/quarto-html/anchor.min.js"></script>
<link href="Homework 1 Sample Solutions_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Homework 1 Sample Solutions_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Homework 1 Sample Solutions_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Homework 1 Sample Solutions_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Homework 1 Sample Solutions_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#part-1-one-variable-analysis" id="toc-part-1-one-variable-analysis" class="nav-link active" data-scroll-target="#part-1-one-variable-analysis">Part 1: One variable analysis</a>
  <ul class="collapse">
  <li><a href="#q1-what-kind-of-dataset-do-we-have-5-points" id="toc-q1-what-kind-of-dataset-do-we-have-5-points" class="nav-link" data-scroll-target="#q1-what-kind-of-dataset-do-we-have-5-points">Q1: What kind of dataset do we have? (5 points)</a></li>
  <li><a href="#q2-literature-review-5-points" id="toc-q2-literature-review-5-points" class="nav-link" data-scroll-target="#q2-literature-review-5-points">Q2: Literature review (5 points)</a></li>
  <li><a href="#q3-describing-the-data-10-points" id="toc-q3-describing-the-data-10-points" class="nav-link" data-scroll-target="#q3-describing-the-data-10-points">Q3: Describing the data (10 points)</a></li>
  <li><a href="#q4-comparing-categorical-variables-10-points" id="toc-q4-comparing-categorical-variables-10-points" class="nav-link" data-scroll-target="#q4-comparing-categorical-variables-10-points">Q4: Comparing categorical variables (10 points)</a></li>
  <li><a href="#q5-understanding-and-comparing-distributions-10-points" id="toc-q5-understanding-and-comparing-distributions-10-points" class="nav-link" data-scroll-target="#q5-understanding-and-comparing-distributions-10-points">Q5: Understanding and comparing distributions (10 points)</a></li>
  <li><a href="#q6-the-normal-distribution-10-points" id="toc-q6-the-normal-distribution-10-points" class="nav-link" data-scroll-target="#q6-the-normal-distribution-10-points">Q6: The Normal distribution (10 points)</a></li>
  </ul></li>
  <li><a href="#part-2-two-variable-analyis" id="toc-part-2-two-variable-analyis" class="nav-link" data-scroll-target="#part-2-two-variable-analyis">Part 2: Two variable analyis</a>
  <ul class="collapse">
  <li><a href="#q7-relationship-between-variables-15-points" id="toc-q7-relationship-between-variables-15-points" class="nav-link" data-scroll-target="#q7-relationship-between-variables-15-points">Q7: Relationship between variables (15 points)</a></li>
  </ul></li>
  <li><a href="#in-conclusion" id="toc-in-conclusion" class="nav-link" data-scroll-target="#in-conclusion">In conclusion</a>
  <ul class="collapse">
  <li><a href="#q8-putting-it-all-together-10-points" id="toc-q8-putting-it-all-together-10-points" class="nav-link" data-scroll-target="#q8-putting-it-all-together-10-points">Q8: Putting it all together (10 points)</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework 1 Sample Solutions</h1>
<p class="subtitle lead">DKU Stats 101 Spring 2023 Session 2</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Anonymous </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 31, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">

</div>
<section id="part-1-one-variable-analysis" class="level2">
<h2 class="anchored" data-anchor-id="part-1-one-variable-analysis">Part 1: One variable analysis</h2>
<section id="q1-what-kind-of-dataset-do-we-have-5-points" class="level3">
<h3 class="anchored" data-anchor-id="q1-what-kind-of-dataset-do-we-have-5-points">Q1: What kind of dataset do we have? (5 points)</h3>
<ul>
<li>According to the definitions in the textbook, describe the Five W’s for this dataset.</li>
</ul>
<blockquote class="blockquote">
<ul>
<li><em>Who</em> : Diamonds</li>
<li><em>What</em> : Features about the diamonds and total sales prices</li>
<li><em>When</em> : Recent, not specified</li>
<li><em>Where</em>: Store Record</li>
<li><em>Why</em> : Identify the key features of diamonds that best determine their price</li>
</ul>
</blockquote>
<ul>
<li>Using the definitions in the textbook, describe the variable type for the following variables (you can review the variable definitions <a href="https://www.kaggle.com/datasets/hrokrin/the-largest-diamond-dataset-currely-on-kaggle">here</a>):</li>
</ul>
<blockquote class="blockquote">
<ul>
<li><em>Categorical variables</em> : <code>cut</code>, <code>color</code></li>
<li><em>Ordinal variables</em>: <code>clarity</code>, <code>cut_quality</code>, <code>symmetry</code>, <code>polish</code></li>
<li><em>Identifiers</em> : <code>id</code></li>
<li><em>Quantitative variables</em>: <code>total_sales_price</code>, <code>carat_weight</code>, <code>meas_length</code>, <code>meas_width</code>, <code>meas_depth</code>, <code>depth_percent</code></li>
</ul>
</blockquote>
<blockquote class="blockquote">
<p><strong>Points of emphasis:</strong></p>
<ul>
<li>You don’t need to know all of the details for where the dataset came from for the Five Ws but you do need to categorize all the variables properly.</li>
</ul>
</blockquote>
</section>
<section id="q2-literature-review-5-points" class="level3">
<h3 class="anchored" data-anchor-id="q2-literature-review-5-points">Q2: Literature review (5 points)</h3>
<p>Example: <a href="https://www.gia.edu/diamond-quality-factor">GIA Diamond Quality Factor</a></p>
<p>A diamond’s value is often affected by the rarity of its clarity, color, cut, and carat weight.</p>
<ol type="1">
<li>Carat weight strongly related to price.</li>
<li>Cut quality strongly related ro price.</li>
<li>Color strongly related to price.</li>
</ol>
<blockquote class="blockquote">
<p><strong>Points of emphasis:</strong></p>
<ul>
<li>The article must deal with diamonds data</li>
</ul>
</blockquote>
</section>
<section id="q3-describing-the-data-10-points" class="level3">
<h3 class="anchored" data-anchor-id="q3-describing-the-data-10-points">Q3: Describing the data (10 points)</h3>
<p>The first step in analyzing any dataset is doing some exploratory analysis of the variables.</p>
<ul>
<li><p>Make a histogram of <code>total_sales_price</code>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-q3a" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Homework-1-Sample-Solutions_files/figure-html/fig-q3a-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Total sales price histogram</figcaption><p></p>
</figure>
</div>
</div>
</div></li>
<li><p>Describe it using the three features of quantitative data.</p></li>
</ul>
<blockquote class="blockquote">
<ul>
<li><p><em>Shape</em>: appears to be right skewed with several outliers at high values, asymmetrical. Unimodal.</p></li>
<li><p><em>Center</em>: mean income is 4966, median is 1343; as you can see, the mean is being “pulled” to higher values due to the right skew.</p></li>
<li><p><em>Spread</em>: IQR is 2903.5, so 50% of the observations fall within 2903.5 dollars, the middle half of the data. The standard deviation is 9227, which is about 300% of the IQR, because the standard deviation is affected by extreme outliers.</p></li>
</ul>
</blockquote>
<ul>
<li>Does the histogram of <code>total_sales_price</code> surprise you? Why or why not?</li>
</ul>
<blockquote class="blockquote">
<ul>
<li>Not really. Right skewed makes sense because rare diamonds are extremely pricy.</li>
</ul>
</blockquote>
<ul>
<li>Which is a better measure of center of the histogram, mean or median?</li>
</ul>
<blockquote class="blockquote">
<ul>
<li>In this case, because of the right skew, the median is a better measure of center.</li>
</ul>
</blockquote>
<ul>
<li><p>Make a nice table displaying the 5 number summary. You can make a nice table using either <a href="https://bookdown.org/yihui/rmarkdown-cookbook/kable.html">kable</a> or with the <a href="https://quarto.org/docs/visual-editor/content.html#editing-tables">visual editing mode</a> of Quarto. Calculate the five number summary by using the <code>min()</code> , <code>quantile()</code>, <code>median()</code>, and <code>max()</code> functions to do this. Show your code.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-q3b" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;1: Total sales price 5 number summary</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Min</th>
<th style="text-align: right;">25%</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">75%</th>
<th style="text-align: right;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">218</td>
<td style="text-align: right;">914</td>
<td style="text-align: right;">1343</td>
<td style="text-align: right;">3817.5</td>
<td style="text-align: right;">61867</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></li>
</ul>
<blockquote class="blockquote">
<p>There are quite a few other ways to generate this result, the above is just one example.</p>
</blockquote>
<ul>
<li>Calculate the standard deviation using the <code>sd()</code> function. Interpret it - is it large or small?</li>
</ul>
<blockquote class="blockquote">
<p>Standard deviation(sd) is a kind of evaluation for how far each value is from the mean, representing the the spread of the data distribution, so standard deviation is often discussed at the same time as the mean. The result of <code>sd()</code> equals to the square root of the variance, with the same unit of the original data, but it can be greatly affected by outliers or skew. In this case, the standard deviation is 9227 which is quite large given that the mean is 4966, besides, most of the data is around $0-$4000 based on the histogram - this is the influence of outliers.</p>
</blockquote>
<ul>
<li>Would this histogram benefit from a transformation, in your opinion? Why or why not? If it would, please transform it appropriately and describe the transformation.</li>
</ul>
<blockquote class="blockquote">
<p>Yes. The distribution is right skewed so lower power transformations transformation could maybe solve the problem of outliers without deforming the distribution too much on the other side. The following figure is the histogram of <code>total_sales_price</code>, which seems more symmertric, though the log form makes it somewhat harder to interpret. Further, more fine tuned transformations might produce better results.</p>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<div id="fig-q3c" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Homework-1-Sample-Solutions_files/figure-html/fig-q3c-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;2: Rexpression of total sales price</figcaption><p></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Make a bar chart comparing the mean of <code>total_sales_price</code> according to the variable <code>cut_quality</code>. Interpret this graph.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-q3d" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Homework-1-Sample-Solutions_files/figure-html/fig-q3d-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3: Total sales price by cut quality</figcaption><p></p>
</figure>
</div>
</div>
</div></li>
</ul>
<blockquote class="blockquote">
<p>This bar chart shows that unknown cut quality has the highest price. A difference in price of ~$9000 is large. Price of excellent-cutted category is only slightly higher than very-good-cutted category. It seems that unknown cut gems indicate a rare cut of a diamond brings a huge price premium.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Points of emphasis:</strong></p>
<ul>
<li>Well labeled graphs, with appropriate (not variable name) names for the <code>x</code> and <code>y</code> axes.</li>
<li>Legend labeled</li>
<li>Bar graphs use color (-1 if not)</li>
<li>Graphs that contain the correct amount of information</li>
<li>Reasonable, thoughtful interpretations of the requested statistics, not just one or two word answers. - Correct results for the requested statistics</li>
</ul>
</blockquote>
</section>
<section id="q4-comparing-categorical-variables-10-points" class="level3">
<h3 class="anchored" data-anchor-id="q4-comparing-categorical-variables-10-points">Q4: Comparing categorical variables (10 points)</h3>
<ul>
<li>One interesting piece of information the jewelry store would like to know is if there is any relationship between the clarity and the cut quality. In particular, they wonder if cut quality might differ between diamonds of higher clarity. The best way to examine this relationship is with a contingency table.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-q4a" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;2: Contingency table of clarity of diamonds on cut quality</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Excellent</th>
<th style="text-align: right;">unknown</th>
<th style="text-align: right;">Very Good</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">I1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">I2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IF</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">SI1</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SI2</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">VS1</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VS2</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">VVS1</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VVS2</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>The question is about diamonds of higher clarity, so we can focus on VS, VVS, IF. Overall, we can see that excellent cuts have the largest counts and very good cuts have the least. With the same clarity category, the ratios of each cut seem about the same.</p>
</blockquote>
<ul>
<li>Add margins to your table. Does it change your interpretation?</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-q4b" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;3: Contingency table w/ margins of clarity of diamonds on cut quality</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Excellent</th>
<th style="text-align: right;">unknown</th>
<th style="text-align: right;">Very Good</th>
<th style="text-align: right;">Sum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">I1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">I2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IF</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">SI1</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">43</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SI2</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">38</td>
</tr>
<tr class="even">
<td style="text-align: left;">VS1</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">45</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VS2</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">43</td>
</tr>
<tr class="even">
<td style="text-align: left;">VVS1</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VVS2</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">27</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sum</td>
<td style="text-align: right;">154</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">250</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Adding margins to the table allows us to see the total count for each row and column, and makes it more clear that the ratio in each cut category is about the same.</p>
</blockquote>
<ul>
<li>Convert your table into a proportions table. Does this better help explain what the data show? What are the advantages and disadvantages of each table type?</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-q4c" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;4: Proportions table of clarity of diamonds on cut quality</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Excellent</th>
<th style="text-align: right;">unknown</th>
<th style="text-align: right;">Very Good</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">I1</td>
<td style="text-align: right;">0.3333333</td>
<td style="text-align: right;">0.6666667</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">I2</td>
<td style="text-align: right;">0.5000000</td>
<td style="text-align: right;">0.5000000</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IF</td>
<td style="text-align: right;">0.7000000</td>
<td style="text-align: right;">0.2000000</td>
<td style="text-align: right;">0.1000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">SI1</td>
<td style="text-align: right;">0.6046512</td>
<td style="text-align: right;">0.2325581</td>
<td style="text-align: right;">0.1627907</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SI2</td>
<td style="text-align: right;">0.4473684</td>
<td style="text-align: right;">0.3421053</td>
<td style="text-align: right;">0.2105263</td>
</tr>
<tr class="even">
<td style="text-align: left;">VS1</td>
<td style="text-align: right;">0.6666667</td>
<td style="text-align: right;">0.2222222</td>
<td style="text-align: right;">0.1111111</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VS2</td>
<td style="text-align: right;">0.6279070</td>
<td style="text-align: right;">0.2325581</td>
<td style="text-align: right;">0.1395349</td>
</tr>
<tr class="even">
<td style="text-align: left;">VVS1</td>
<td style="text-align: right;">0.7027027</td>
<td style="text-align: right;">0.1351351</td>
<td style="text-align: right;">0.1621622</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VVS2</td>
<td style="text-align: right;">0.6666667</td>
<td style="text-align: right;">0.1851852</td>
<td style="text-align: right;">0.1481481</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>In this case, I prefer the proportion table–it is easier to see the relative count of percents according to clarity category.</p>
</blockquote>
<blockquote class="blockquote">
<ul>
<li>The advantage of the count table is that it gives a clear idea of the actual number of diamonds in each category, which may be important for certain analyses.</li>
<li>The advantage of the proportions table is that it shows the distribution of categories within each group, which can be useful for comparing between categories and identifying patterns.</li>
<li>The disadvantage of the proportions table is that it does not show the actual number of diamonds in each category.</li>
</ul>
</blockquote>
<blockquote class="blockquote">
<p><strong>Points of emphasis:</strong></p>
<ul>
<li>Reasonable, thoughtful interpretations of the requested statistics, not just one or two word answers.</li>
<li>Correct results for the requested statistics</li>
</ul>
</blockquote>
</section>
<section id="q5-understanding-and-comparing-distributions-10-points" class="level3">
<h3 class="anchored" data-anchor-id="q5-understanding-and-comparing-distributions-10-points">Q5: Understanding and comparing distributions (10 points)</h3>
<ul>
<li><p>Using the five number summaries, calculate if <code>carat_weight</code> or <code>meas_width</code> have any outliers according to the rule described in the textbook for outliers in boxplots. Show your code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">kable</span>(diamonds.recent.sales <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="fu">min</span>(carat_weight),  <span class="fu">quantile</span>(carat_weight, <span class="at">probs=</span><span class="fl">0.25</span>), <span class="fu">median</span>(carat_weight), <span class="fu">quantile</span>(carat_weight, <span class="at">probs=</span><span class="fl">0.75</span>), <span class="fu">max</span>(carat_weight)), </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Min"</span>, <span class="st">"25%"</span>, <span class="st">"Median"</span>, <span class="st">"75%"</span>, <span class="st">"Max"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-q5a1-1" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;5: Carat weight 5 number summary</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Min</th>
<th style="text-align: right;">25%</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">75%</th>
<th style="text-align: right;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">0.415</td>
<td style="text-align: right;">0.735</td>
<td style="text-align: right;">5.2</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  diamonds.recent.sales <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="fu">min</span>(meas_width),  <span class="fu">quantile</span>(meas_width, <span class="at">probs=</span><span class="fl">0.25</span>), <span class="fu">median</span>(meas_width), <span class="fu">quantile</span>(meas_width, <span class="at">probs=</span><span class="fl">0.75</span>), <span class="fu">max</span>(meas_width)), </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Min"</span>, <span class="st">"25%"</span>, <span class="st">"Median"</span>, <span class="st">"75%"</span>, <span class="st">"Max"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-q5a1-2" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;6: Measured width 5 number summary</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Min</th>
<th style="text-align: right;">25%</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">75%</th>
<th style="text-align: right;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2.82</td>
<td style="text-align: right;">4.28</td>
<td style="text-align: right;">4.55</td>
<td style="text-align: right;">5.38</td>
<td style="text-align: right;">9.52</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></li>
</ul>
<blockquote class="blockquote">
<p>For <code>carat_weight:</code></p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>carat_weight_med <span class="ot">&lt;-</span> <span class="fu">median</span>(diamonds.recent.sales<span class="sc">$</span>carat_weight)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>carat_weight_lq <span class="ot">&lt;-</span> <span class="fu">quantile</span>(diamonds.recent.sales<span class="sc">$</span>carat_weight, <span class="at">probs=</span><span class="fl">0.25</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>carat_weight_uq <span class="ot">&lt;-</span> <span class="fu">quantile</span>(diamonds.recent.sales<span class="sc">$</span>carat_weight, <span class="at">probs=</span><span class="fl">0.75</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>carat_weight_iqr <span class="ot">&lt;-</span> <span class="fu">IQR</span>(diamonds.recent.sales<span class="sc">$</span>carat_weight)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>carat_weight_uf <span class="ot">&lt;-</span> carat_weight_uq <span class="sc">+</span> <span class="fl">1.5</span><span class="sc">*</span>carat_weight_iqr</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>carat_weight_lf <span class="ot">&lt;-</span> carat_weight_lq <span class="sc">-</span> <span class="fl">1.5</span><span class="sc">*</span>carat_weight_iqr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<ul>
<li><span class="math inline">\(median=0.415\)</span></li>
<li><span class="math inline">\(IQR=0.735-0.3=0.435\)</span></li>
<li><span class="math inline">\(Upper\,fence=0.735+1.5\cdot0.435=1.3875\)</span></li>
<li><span class="math inline">\(Lower\,fence=0.3-1.5\cdot0.435=-0.3525\)</span> or <span class="math inline">\(0\)</span></li>
<li>According to this rule, there are upper outliers of <code>carat_weight</code>.</li>
</ul>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-q5a3" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;7: Outlier identities for carat weight</caption>
<thead>
<tr class="header">
<th style="text-align: right;">ID</th>
<th style="text-align: right;">Carat Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">216202</td>
<td style="text-align: right;">5.20</td>
</tr>
<tr class="even">
<td style="text-align: right;">218358</td>
<td style="text-align: right;">4.04</td>
</tr>
<tr class="odd">
<td style="text-align: right;">208845</td>
<td style="text-align: right;">3.52</td>
</tr>
<tr class="even">
<td style="text-align: right;">213368</td>
<td style="text-align: right;">3.21</td>
</tr>
<tr class="odd">
<td style="text-align: right;">209661</td>
<td style="text-align: right;">3.08</td>
</tr>
<tr class="even">
<td style="text-align: right;">215192</td>
<td style="text-align: right;">3.05</td>
</tr>
<tr class="odd">
<td style="text-align: right;">215956</td>
<td style="text-align: right;">3.01</td>
</tr>
<tr class="even">
<td style="text-align: right;">215254</td>
<td style="text-align: right;">2.50</td>
</tr>
<tr class="odd">
<td style="text-align: right;">207940</td>
<td style="text-align: right;">2.28</td>
</tr>
<tr class="even">
<td style="text-align: right;">207759</td>
<td style="text-align: right;">2.20</td>
</tr>
<tr class="odd">
<td style="text-align: right;">199564</td>
<td style="text-align: right;">2.13</td>
</tr>
<tr class="even">
<td style="text-align: right;">209083</td>
<td style="text-align: right;">2.02</td>
</tr>
<tr class="odd">
<td style="text-align: right;">205697</td>
<td style="text-align: right;">2.01</td>
</tr>
<tr class="even">
<td style="text-align: right;">202846</td>
<td style="text-align: right;">2.01</td>
</tr>
<tr class="odd">
<td style="text-align: right;">204256</td>
<td style="text-align: right;">1.91</td>
</tr>
<tr class="even">
<td style="text-align: right;">194890</td>
<td style="text-align: right;">1.81</td>
</tr>
<tr class="odd">
<td style="text-align: right;">209635</td>
<td style="text-align: right;">1.71</td>
</tr>
<tr class="even">
<td style="text-align: right;">194603</td>
<td style="text-align: right;">1.70</td>
</tr>
<tr class="odd">
<td style="text-align: right;">199242</td>
<td style="text-align: right;">1.57</td>
</tr>
<tr class="even">
<td style="text-align: right;">200418</td>
<td style="text-align: right;">1.54</td>
</tr>
<tr class="odd">
<td style="text-align: right;">195785</td>
<td style="text-align: right;">1.51</td>
</tr>
<tr class="even">
<td style="text-align: right;">188484</td>
<td style="text-align: right;">1.51</td>
</tr>
<tr class="odd">
<td style="text-align: right;">181747</td>
<td style="text-align: right;">1.51</td>
</tr>
<tr class="even">
<td style="text-align: right;">188277</td>
<td style="text-align: right;">1.50</td>
</tr>
<tr class="odd">
<td style="text-align: right;">206744</td>
<td style="text-align: right;">1.50</td>
</tr>
<tr class="even">
<td style="text-align: right;">203185</td>
<td style="text-align: right;">1.50</td>
</tr>
<tr class="odd">
<td style="text-align: right;">189437</td>
<td style="text-align: right;">1.50</td>
</tr>
<tr class="even">
<td style="text-align: right;">203212</td>
<td style="text-align: right;">1.50</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>For <code>meas_width</code>:</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a> meas_width_med <span class="ot">&lt;-</span> <span class="fu">median</span>(diamonds.recent.sales<span class="sc">$</span>meas_width)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a> meas_width_lq <span class="ot">&lt;-</span> <span class="fu">quantile</span>(diamonds.recent.sales<span class="sc">$</span>meas_width, <span class="at">probs=</span><span class="fl">0.25</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a> meas_width_uq <span class="ot">&lt;-</span> <span class="fu">quantile</span>(diamonds.recent.sales<span class="sc">$</span>meas_width, <span class="at">probs=</span><span class="fl">0.75</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a> meas_width_iqr <span class="ot">&lt;-</span> <span class="fu">IQR</span>(diamonds.recent.sales<span class="sc">$</span>meas_width)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a> meas_width_uf <span class="ot">&lt;-</span> meas_width_uq <span class="sc">+</span> <span class="fl">1.5</span><span class="sc">*</span>meas_width_iqr</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a> meas_width_lf <span class="ot">&lt;-</span> meas_width_lq <span class="sc">-</span> <span class="fl">1.5</span><span class="sc">*</span>meas_width_iqr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<ul>
<li><span class="math inline">\(median=4.55\)</span></li>
<li><span class="math inline">\(IQR=5.38-4.28=1.1\)</span></li>
<li><span class="math inline">\(Upper\,fence=5.38+1.5\cdot1.1=7.03\)</span></li>
<li><span class="math inline">\(Lower\,fence=4.28-1.5\cdot1.1=2.63\)</span></li>
<li>According to this rule, there’re upper outliers of <code>meas_width</code>.</li>
</ul>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-q5a5" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;8: Outlier identities for measured width</caption>
<thead>
<tr class="header">
<th style="text-align: right;">ID</th>
<th style="text-align: right;">Measured width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">216202</td>
<td style="text-align: right;">9.52</td>
</tr>
<tr class="even">
<td style="text-align: right;">213368</td>
<td style="text-align: right;">9.40</td>
</tr>
<tr class="odd">
<td style="text-align: right;">215956</td>
<td style="text-align: right;">9.40</td>
</tr>
<tr class="even">
<td style="text-align: right;">209083</td>
<td style="text-align: right;">8.49</td>
</tr>
<tr class="odd">
<td style="text-align: right;">199564</td>
<td style="text-align: right;">8.21</td>
</tr>
<tr class="even">
<td style="text-align: right;">209661</td>
<td style="text-align: right;">8.16</td>
</tr>
<tr class="odd">
<td style="text-align: right;">207759</td>
<td style="text-align: right;">8.12</td>
</tr>
<tr class="even">
<td style="text-align: right;">205697</td>
<td style="text-align: right;">8.07</td>
</tr>
<tr class="odd">
<td style="text-align: right;">194890</td>
<td style="text-align: right;">7.77</td>
</tr>
<tr class="even">
<td style="text-align: right;">215254</td>
<td style="text-align: right;">7.55</td>
</tr>
<tr class="odd">
<td style="text-align: right;">218358</td>
<td style="text-align: right;">7.48</td>
</tr>
<tr class="even">
<td style="text-align: right;">203185</td>
<td style="text-align: right;">7.39</td>
</tr>
<tr class="odd">
<td style="text-align: right;">206744</td>
<td style="text-align: right;">7.36</td>
</tr>
<tr class="even">
<td style="text-align: right;">188277</td>
<td style="text-align: right;">7.30</td>
</tr>
<tr class="odd">
<td style="text-align: right;">208845</td>
<td style="text-align: right;">7.19</td>
</tr>
<tr class="even">
<td style="text-align: right;">215192</td>
<td style="text-align: right;">7.18</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<ul>
<li>Create a graph of boxplot of <code>meas_width</code> by <code>cut_quality</code>. What can you conclude about <code>meas_width</code> from this display? Would any of these subgroups benefit from having <code>meas_width</code> re-expressed? Why or why not?</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-q5b" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Homework-1-Sample-Solutions_files/figure-html/fig-q5b-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;4: Measured width by category</figcaption><p></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>The distribution of <code>meas_width</code> for the diamonds with excellent cut and very good cut are right skewed, while the distribution of <code>meas width</code> for the diamonds with unknown cut are slightly right skewed(given that mediam is smaller than mean, the majority of outliers are of high values). These sub-distributions may benefit from a log type transformation but one would need to check to make sure.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Points of emphasis:</strong></p>
<ul>
<li>Boxplots well labeled, with no legend (-1 if legend)</li>
<li>Proper calculation of 5 number summaries</li>
<li>Shows work for calcuation of outliers</li>
<li>Discusses shape, center, and spread for analysis of boxplot</li>
<li>Shows understanding of appropriate conditions for reexpression</li>
</ul>
</blockquote>
</section>
<section id="q6-the-normal-distribution-10-points" class="level3">
<h3 class="anchored" data-anchor-id="q6-the-normal-distribution-10-points">Q6: The Normal distribution (10 points)</h3>
<p>Another client of the firm, a ring maker, is interested in producing rings for the diamonds. The ring maker is working on the assumption that the diamond depth (the most important measurement for ring making) can be modeled based on a normal distribution with a mean of 3.2 and a standard distribution of 0.9.</p>
<ul>
<li>In formal notation, write the Normal model the ring maker proposes for the diamonds</li>
</ul>
<blockquote class="blockquote">
<p><span class="math inline">\(N(3.2, 0.9)\)</span></p>
</blockquote>
<ul>
<li>What features of <code>meas_depth</code> would change if we reexpressed the measured depth in inches instead of centimeters?</li>
</ul>
<blockquote class="blockquote">
<p>The specific values for measures of center and spread would change, but the data’s relationship with each other would remain the same.</p>
</blockquote>
<ul>
<li>Would it be reasonable for the ring maker to introduce a ring that could accept diamonds with a depth of 4 cm to 2 cm? Explain.</li>
</ul>
<blockquote class="blockquote">
<p>It would depend on the costs of making such a ring, but since the range given is about <span class="math inline">\(\pm1\)</span> standard deviation from the mean, it would fit about 65% of the diamonds, which seems like a reasonably large percent of the diamond market.</p>
</blockquote>
<ul>
<li>Approximately what percent of diamonds would fit into this proposed ring? Show your work.</li>
</ul>
<p>Assuming the Normal model as specified in the Question 6 description, the bottom half would be:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean - lower value / sd</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>z.score.lower <span class="ot">&lt;-</span> (<span class="dv">2</span> <span class="sc">-</span> <span class="fl">3.2</span>) <span class="sc">/</span> <span class="fl">0.9</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Get lower percentage; pnorm gives the exact probability point and subtract</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># from the mean to get the total probability mass</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>lower.percent <span class="ot">&lt;-</span> <span class="fl">0.5</span> <span class="sc">-</span> <span class="fu">pnorm</span>(z.score.lower)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(lower.percent, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.41</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean - lower value / sd</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>z.score.upper <span class="ot">&lt;-</span> (<span class="dv">4</span> <span class="sc">-</span> <span class="fl">3.2</span>) <span class="sc">/</span> <span class="fl">0.9</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Get lower percentage; pnorm gives the exact probability point and subtract</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># this from the mean to get the upper half probility</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>upper.percent <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(z.score.upper) <span class="sc">-</span> <span class="fl">0.5</span> </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(upper.percent, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.31</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(upper.percent <span class="sc">+</span> lower.percent, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.72</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>About 72% of diamonds would fit into this proposed ring, assuming Normal probability.</p>
</blockquote>
<p>In reality, we can find the same figure directly in our dataset with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the cumulative probability distribution of the variable</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>mdepth.cum.dist <span class="ot">&lt;-</span> <span class="fu">ecdf</span>(diamonds.recent.sales<span class="sc">$</span>meas_depth)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mdepth.cum.dist</span>(<span class="dv">4</span>) <span class="sc">-</span> <span class="fu">mdepth.cum.dist</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.88</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>In the dataset provided to you, the range between 2 and 4 includes about 88% of the diamonds.</p>
</blockquote>
<ul>
<li>Estimate the IQR of the diamond size and show your work for how you arrived at that estimate.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(diamonds.recent.sales<span class="sc">$</span>meas_depth, <span class="at">probs=</span><span class="fl">0.75</span>) <span class="sc">-</span> <span class="fu">quantile</span>(diamonds.recent.sales<span class="sc">$</span>meas_depth, <span class="at">probs=</span><span class="fl">0.25</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   75% 
0.7425 </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The IQR is 0.7425.</p>
</blockquote>
<ul>
<li>Using the Normal model for <code>meas_depth</code>, between what range should 2.5% and 97.5% of the diamond depths be between? How about between 16% and 84%? Show all work.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Range between 2.5% and 97.5%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>((<span class="fu">qnorm</span>(<span class="fl">0.025</span>) <span class="sc">*</span> <span class="fl">0.9</span>) <span class="sc">+</span> <span class="fl">3.2</span>, (<span class="fu">qnorm</span>(<span class="fl">0.975</span>) <span class="sc">*</span> <span class="fl">0.9</span>) <span class="sc">+</span> <span class="fl">3.2</span>), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.44 4.96</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Range between 16% and 84%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>((<span class="fu">qnorm</span>(<span class="fl">0.16</span>) <span class="sc">*</span> <span class="fl">0.9</span>) <span class="sc">+</span> <span class="fl">3.2</span>, (<span class="fu">qnorm</span>(<span class="fl">0.84</span>) <span class="sc">*</span> <span class="fl">0.9</span>) <span class="sc">+</span> <span class="fl">3.2</span>), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.3 4.1</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>With the normal model, the 2.5% and 97.5% of the diamond depths should between ~1.44 and ~4.96. The 16% and 84% of the diamond depths should between ~2.3 and ~4.1.</p>
</blockquote>
<ul>
<li>Using the <code>quantile()</code> function, find the actual range <code>meas_depth</code> that is between 2.5% and 97.5% percentiles and between 16% and 84%. Why are the results different than the those obtained in the previous question?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">quantile</span>(diamonds.recent.sales<span class="sc">$</span>meas_depth, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>)), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 2.5% 97.5% 
 2.26  5.20 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">quantile</span>(diamonds.recent.sales<span class="sc">$</span>meas_depth, <span class="fu">c</span>(<span class="fl">0.16</span>, <span class="fl">0.84</span>)), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 16%  84% 
2.61 3.79 </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The actual 2.5% and 97.5% percentile are ~2.26 and ~5.20.The 16% and 84% percentile are ~2.61 and ~3.79. The results indicate that the distribution is not perfectly normal and is somewhat more compressed than one would expect for a normal distribution. This likely indicates some outliers inflating the size of the standard deviation.</p>
</blockquote>
</section>
</section>
<section id="part-2-two-variable-analyis" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="part-2-two-variable-analyis">Part 2: Two variable analyis</h2>
<section id="q7-relationship-between-variables-15-points" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="q7-relationship-between-variables-15-points">Q7: Relationship between variables (15 points)</h3>
<ul>
<li>Make two scatterplots (side by side) of <code>total_sales_price</code> as a function of <code>carat_weight</code> and a second plot of the same relationship colored by <code>cut_quality</code>. Add a linear smoother to both plots (in the second plot there should be a smoother for each level of <code>cut_quality</code>) and label any points you consider to be an outlier using <code>geom_text()</code> - the label for the outlier should print the observation’s <code>id</code>.</li>
</ul>
<div class="cell column-page quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-q7a-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Homework-1-Sample-Solutions_files/figure-html/fig-q7a-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;5: Total sales vs.&nbsp;carat weight</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-q7a-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Homework-1-Sample-Solutions_files/figure-html/fig-q7a-2.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;6: Total sales vs.&nbsp;carat weight by cut quality</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
<ol type="1">
<li>For the first graph, do you think there is a clear pattern? Describe the association between <code>total_sales_price</code> and <code>carat_weight</code>.</li>
</ol>
<blockquote class="blockquote">
<p>There appears to be a positive linear relationship.</p>
<ul>
<li>Direction - Positive</li>
<li>Form - Linear</li>
<li>Strength - Medium; There are many observations below the linear regression, perhaps the relationship might vary by category?</li>
<li>Outliers - There is one serious outlier but probably not enough to strong influence the relationship.</li>
</ul>
</blockquote>
<ol start="2" type="1">
<li>Find out the details of any outliers you have identified. Do you think the outlier(s) should be excluded from the analysis? Why or why not?</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-q7b" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;9: Total sales vs.&nbsp;carat weight outlier</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 24%">
<col style="width: 17%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">ID</th>
<th style="text-align: right;">Total sales price</th>
<th style="text-align: right;">Carat weight</th>
<th style="text-align: left;">Color</th>
<th style="text-align: left;">Clarity</th>
<th style="text-align: left;">Symmetry</th>
<th style="text-align: left;">Polish</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">216340</td>
<td style="text-align: right;">51638</td>
<td style="text-align: right;">0.51</td>
<td style="text-align: left;">unknown</td>
<td style="text-align: left;">VS2</td>
<td style="text-align: left;">Good</td>
<td style="text-align: left;">Excellent</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>The outlier is the 216340th observation - nothing about any of the variable values looks like an obvious mistake. Additional investigation may be warranted to determine why this observation is an outlier. Without any other information, we should probably continue to include it in the dataset.</p>
</blockquote>
<ol start="3" type="1">
<li>Does the relationship meaningfully change when colored by <code>cut_quality</code>?</li>
</ol>
<blockquote class="blockquote">
<p>The relationship meaningfully changes when colored by <code>cut_quality</code>. There is a flatter slope for very good cut diamonds, indicating that <code>carat_weight</code> has less of a relationship with price for lower quality cuts.</p>
</blockquote>
<ol start="4" type="1">
<li>What do you estimate the correlation for the first graph to be, without using technology?</li>
</ol>
<blockquote class="blockquote">
<p>I estimate the coorelation to be around 0.8.</p>
</blockquote>
<ol start="5" type="1">
<li>Check the conditions for correlation</li>
</ol>
<blockquote class="blockquote">
<ul>
<li>Quantitative variables condition: both are quantitative</li>
<li>Straight enough condition: the relationship is straight</li>
<li>No outliers condition: there is an outliers that might affect the correlation, though probably will not result in a big change in the estimate.</li>
</ul>
</blockquote>
<ol start="6" type="1">
<li>Find and interpret the correlation coefficient for this relationship</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(diamonds.recent.sales<span class="sc">$</span>carat_weight, diamonds.recent.sales<span class="sc">$</span>total_sales_price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8750655</code></pre>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li>The correlation is ~0.88, that indicates a very strong relationship. Price and weight seem to be highly related..</li>
</ul>
</blockquote>
<ol start="7" type="1">
<li>When interpreting these two graphs, what can we learn about the relationship between these variables?</li>
</ol>
<blockquote class="blockquote">
<ul>
<li>The <code>total_sales_price</code> is strongly positive linearly associated with the <code>carat_weight</code>, the relationship is stronger for unknown cuts and excellent cuts.</li>
</ul>
</blockquote>
</section>
</section>
<section id="in-conclusion" class="level2">
<h2 class="anchored" data-anchor-id="in-conclusion">In conclusion</h2>
<section id="q8-putting-it-all-together-10-points" class="level3">
<h3 class="anchored" data-anchor-id="q8-putting-it-all-together-10-points">Q8: Putting it all together (10 points)</h3>
<p>Through the analysis conducted in the previous section <strong>and through at least one additional investigation of your own (which can be an additional graph, table, or calculation)</strong>, write two to three paragraphs outlining what you think are the main findings of questions 1-7 and your additional graph, table, or calculation. What would you recommend to your boss as to what types of diamonds sell for the most money? What information are we missing in this dataset that we would need to better understand diamond price?</p>
<blockquote class="blockquote">
<p><strong>Points of emphasis:</strong></p>
<ul>
<li>Analysis here can vary but must be at least two paragraphs</li>
<li>Should accurately summarize the information discovered by answering the previous questions</li>
<li>B-level answer will conduct a shallow additional analysis, A-level answer will show interesting additional analysis that builds on previous answers</li>
<li>Shows a good understanding of the limits of this dataset</li>
<li>Should be as precise as possible, don’t use general statements when you can be more specific</li>
</ul>
</blockquote>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>